# Generated by Django 3.2.9 on 2021-12-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211215_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='usuario',
            new_name='user',
        ),
    ]
