# Generated by Django 4.0 on 2021-12-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211216_2332'),
        ('api', '0006_rename_comments_comment_comment'),
    ]

    operations = [
    ]
